log dir: log
logging config:
  formatters:
    brief:
      format: line:%(lineno)d-%(levelname)s - %(message)s
    simple:
      format: '%(asctime)s - %(module)s.%(funcName)s:%(lineno)d - %(levelname)s -
        %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: INFO
      stream: null
    error:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: error.log
      formatter: simple
      level: ERROR
      maxBytes: 10485760
    file:
      class: logging.FileHandler
      filename: debug.log
      formatter: simple
      level: WARNING
  loggers:
    simpleExample:
      handlers:
      - console
      - file
      - error
      level: DEBUG
      propagate: false
  root:
    handlers:
    - console
    - error
    level: DEBUG
  version: 1
scripts dir: script
software dir: E:/CASIProject/CASI003/CASI003
using script: test.yaml
